name: local-k8s
description: Deploy a Docker image to a local Kubernetes cluster.

inputs:
  release-name:
    description: 'Helm release name'
    required: true
  namespace:  
    description: 'Kubernetes namespace to deploy to'
    required: false
    default: 'default'  
  registry:
    description: 'Container registry. Example: ghcr.io'
    required: false
    default: 'ghcr.io'
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: 'Docker image tag'
    required: false
    default: 'latest'
  chart: 
    description: 'Helm chart path. If set to "app" this will use the built in helm chart found in this repository'
    required: true
    default: 'app'
  helm-version:
    description: 'Helm version to use: helm or helm3. Defaults to helm3'
    required: false
    default: 'helm3'
  
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Deploy to local Kubernetes cluster
      shell: bash
      run: |
        echo "Deploying ${{ inputs.release-name }} to Kubernetes namespace ${{ inputs.namespace }}"
        echo "Using Helm chart: ${{ inputs.chart }}"
        echo "Image: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"
        echo "Helm version: ${{ inputs.helm-version }}"

        helm upgrade --install ${{ inputs.release-name }} ${{ inputs.chart }} \
          --namespace ${{ inputs.namespace }} \
          --set image.repository=${{ inputs.registry }}/${{ inputs.image-name }} \
          --set image.tag=${{ inputs.image-tag }} \
          --set imagePullPolicy=IfNotPresent \
          --debug
          
          
