name: Complete node Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: '20'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'npm run lint'
        type: string

      build-command:
        description: 'build command (e.g., npm run)'
        required: false
        default: 'npm run build'
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'npm test'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'npm pack'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'node-package'
        type: string
      
      run_trivy:
        description: 'Run Trivy Scan'
        required: false
        default: true
        type: boolean



jobs:
  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
    # This job sets up Node.js and runs the lint command
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node/setup@testing
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job sets up Node.js and runs the lint command
      - uses:  altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/lint@main
        with:
          lint-command: ${{ inputs.lint-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.contine-on-error }}


  # This job builds the Node.js project, preparing it for packaging
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      
      # This job sets up Node.js and runs the build command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/build@main
        with:
          build-command: ${{ inputs.build-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # This job executes unit test
  unitTest:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This job sets up Node.js and runs unit tests
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@main
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
      # This step runs the unit tests using Jest
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/jest-unit-test@main
        with:
          test-command: ${{ inputs.test-command }}
          continue-on-error: ${{ inputs.contine-on-error }}

  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  # securityScan:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     security-events: write
  #     actions: read
  #     contents: read
  #   steps:
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      # - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/codeql@testing
      #   with:
      #     languages: javascript
 
  
  # This job handles versioning by generating a new tag based on the commit history
  versioning:
    runs-on: ubuntu-latest
    needs: [build, unitTest]
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      # This step checks out the code from the repository
      - id: generate-tag
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/git-tag-generation@main

  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  dockerBuildAndPush:
    runs-on: ubuntu-latest
    needs: versioning
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/docker-build-push@main
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  dockerScan:
    runs-on: ubuntu-latest
    needs: [versioning, dockerBuildAndPush]
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: read  # Required to pull from GHCR
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/trivy-scan@main
        if: ${{ inputs.run_trivy == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'

      # This job scans the Docker image for vulnerabilities using Grype
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/grype-scan@main
        if: ${{ inputs.run_grype == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # This job packages the Node.js project, creating an artifact for deployment or distribution
  package:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      # This job sets up Node.js in the environment
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@main
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: '.'
      # This step packages the Node.js project
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/git-package@main
        with:
          package-command: ${{ inputs.package-command }}
          artifact-name: ${{ inputs.artifact-name }}
  
  dashboard:
    runs-on: ubuntu-latest
    needs: [dockerScan, lint, unitTest, build]
    steps:
      # This step builds the dashboard HTML file from the reports
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/github-dashboard@testing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tool: 'CI Dashboard'
          report: 'reports'
          critical_keyword: 'CRITICAL'
          high_keyword: 'HIGH'

