name: security-scan

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the Docker image to scan'
        required: true
        type: string
      image-tag:
        description: 'Tag of the Docker image to scan'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.image-name || github.event.repository.name }}  
  IMAGE_TAG: ${{ inputs.image-tag || 'latest' }}      
  
jobs:
  scan_docker_image:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Log in to the Container registry üì¶
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Docker image üê≥
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Snyk report as sarif üì¶
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
  